// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Student.proto

package com.dylan.proto;

public interface MyRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.dylan.proto.MyRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * "option string username=1;" can not add the key word "option"
     * </pre>
     *
     * <code>string username = 1;</code>
     */
    java.lang.String getUsername();

    /**
     * <pre>
     * "option string username=1;" can not add the key word "option"
     * </pre>
     *
     * <code>string username = 1;</code>
     */
    com.google.protobuf.ByteString
    getUsernameBytes();
}
